"""
Django settings for globalconceptBE project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (for local dev)
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%%jjte3p!n@u8u9m9*@6-aibu9n71e3r-+d_1q(db8lj=@#6kz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("1", "true", "yes", "on")

# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['*']

ALLOWED_HOSTS = [
    "backend.grazconcept.com.ng",
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "grazconcept.com.ng",
    "www.grazconcept.com.ng",
    "app.grazconcept.com.ng",
    "grazconcept-fe.vercel.app",
    "grazconceptbe.onrender.com",  # Added as per instruction
    # "https://grazconceptbe.onrender.com/",  # Removed as per Django's CORS validation requirements
]

# APPEND_SLASH = False

# DO NOT use wildcard with credentials. Comment out CORS_ALLOW_ALL_ORIGINS
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "https://grazconcept-fe.vercel.app", 
    'http://localhost:5174',
    'http://localhost:5173',
    'https://app.grazconcept.com.ng',
    'https://grazconceptbe.onrender.com',  # Added as per instruction
    # 'https://grazconceptbe.onrender.com/',  # Removed: as per CORS origin spec, no trailing slash allowed
]

# If you want to allow credentials (cookies/Authorization), this MUST be True.
CORS_ALLOW_CREDENTIALS = True

# Trusted origin settings for admin/Csrf compliance
CSRF_TRUSTED_ORIGINS = [
    "https://backend.grazconcept.com.ng",
    "https://grazconcept.com.ng",
    "https://www.grazconcept.com.ng",
    "https://app.grazconcept.com.ng",
    "https://grazconcept-fe.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
    "http://localhost:5174",
    "https://grazconceptbe.onrender.com",   # Added as per instruction
    "https://grazconceptbe.onrender.com/",  # (as given, exact form -- Django tolerates this for CSRF, but not for CORS)
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'account',    
    'app',
    'definition',
    'drf_yasg',
    'rest_framework',
    'corsheaders',
    'import_export',
    'rest_framework.authtoken',
    'wallet',
    'notification',
    'channels',
    'chat',


    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'globalconceptBE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'globalconceptBE.wsgi.application'
ASGI_APPLICATION = 'globalconceptBE.asgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # optionally keep session authentication for browsable API
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# CHANNEL_LAYERS needs a working REDIS_URL set as an environment variable for the project to start.
# If REDIS_URL is not defined, Channels will error out on startup (e.g., with Daphne); see error in file_context_0.
# The following fallback allows server start even if REDIS_URL is not set,
# but disables websocket functionality until REDIS_URL is properly configured.
REDIS_URL = os.getenv("REDIS_URL", None)
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Dummy backend prevents crashes but disables channels for development
    # This will result in warnings and timeouts for websocket disconnects as seen in file_context_0.
    # WebSocket (Channels) support will be non-functional in this mode!
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

# ---- Celery configuration ----
# If REDIS_URL is set, use it for Celery as both the broker and backend.
# Otherwise, fallback to a local Redis server (for development).
CELERY_BROKER_URL = REDIS_URL or "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = REDIS_URL or "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Periodic tasks example (see also tasks.py guide)
CELERY_BEAT_SCHEDULE = {
    "process-recurring-savings-plans": {
        "task": "wallet.saving_plans.tasks.process_recurring_savings_plans",
        "schedule": 86400.0,  # Every day (in seconds), adjust as needed.
    },
}


AUTHENTICATION_BACKENDS = [
    'account.backends.EmailBackend',  # Custom email authentication backend
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend
]

# Let WhiteNoise compress and cache static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,  # ensures SSL for production DB
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

AUTH_USER_MODEL = 'account.User'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Cloudinary credentials from environment variables
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

# Use Cloudinary for default media storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AVIATIONSTACK_API_KEY = os.environ.get('AVIATIONSTACK_API_KEY')
AMADEUS_CLIENT_ID = os.environ.get('AMADEUS_CLIENT_ID')
AMADEUS_CLIENT_SECRET = os.environ.get('AMADEUS_CLIENT_SECRET')